package com.dronecontrol.data

/**
 * Immutable snapshot of real-time drone telemetry generated by the flight controller
 * or simulated by the MockDroneConnection.
 */
data class Telemetry(
    val batteryPercentage: Int = 100,
    val batteryVoltage: Float = 12.6f,
    val altitude: Float = 0.0f,            // Altitude above sea level (m)
    val relativeAltitude: Float = 0.0f,    // Altitude above ground/home (m)
    val latitude: Double = 37.774929,      // Default test coords (San Francisco or user base)
    val longitude: Double = -122.419416,
    val heading: Float = 0.0f,             // Compass heading 0-360 degrees
    val groundSpeed: Float = 0.0f,         // Horizontal speed (m/s)
    val verticalSpeed: Float = 0.0f,       // Climb/descent rate (m/s)
    val gpsFix: GpsFix = GpsFix.NO_FIX,
    val satelliteCount: Int = 0,
    val isArmed: Boolean = false,
    val flightMode: FlightMode = FlightMode.STABILIZE,
    val connectionState: ConnectionState = ConnectionState.DISCONNECTED,
    val roll: Float = 0.0f,                // Attitude roll in degrees (-180 to +180)
    val pitch: Float = 0.0f,               // Attitude pitch in degrees (-90 to +90)
    val yaw: Float = 0.0f,                 // Attitude yaw in degrees
    val distanceToHome: Float = 0.0f,      // Distance from armed home point (m)
    val timestamp: Long = System.currentTimeMillis()
) {
    val isAirborne: Boolean
        get() = isArmed && relativeAltitude > 0.3f
}
